databases:
  - name: murasaki
    databaseName: murasaki
    user: murasaki

services:
  - type: web
    name: murasaki
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "DJANGO_SETTINGS_MODULE=murasaki.settings.prod gunicorn murasaki.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: murasaki
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4