# Generated by Django 4.2.8 on 2023-12-25 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagetranslation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='intro'),
        ),
    ]
