# Generated by Django 4.2.8 on 2023-12-25 19:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_pagetranslation_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='music', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='news', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='intro'),
        ),
        migrations.CreateModel(
            name='TourDateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='venue')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description')),
                ('live', models.BooleanField(default=False, verbose_name='live')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.tourdate')),
            ],
            options={
                'verbose_name': 'tour date Translation',
                'db_table': 'pages_tourdate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('intro', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='body')),
                ('live', models.BooleanField(default=False, verbose_name='live')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.newsitem')),
            ],
            options={
                'verbose_name': 'news item Translation',
                'db_table': 'pages_newsitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MusicItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description')),
                ('live', models.BooleanField(default=False, verbose_name='live')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.musicitem')),
            ],
            options={
                'verbose_name': 'music item Translation',
                'db_table': 'pages_musicitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
