# Generated by Django 4.2.8 on 2023-12-25 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_tourdatetranslation_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsitemtranslation',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='tourdatetranslation',
            name='location',
        ),
        migrations.AddField(
            model_name='musicitemtranslation',
            name='image',
            field=models.ImageField(blank=True, upload_to='music', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='newsitemtranslation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitemtranslation',
            name='image',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='newsitemtranslation',
            name='title',
            field=models.CharField(default='title', max_length=300, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourdatetranslation',
            name='date',
            field=models.DateField(default='2023-12-11', verbose_name='date'),
            preserve_default=False,
        ),
    ]
