# Generated by Django 4.2.8 on 2023-12-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_musicrelease_musicreleasetranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicitemtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='musicitemtranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='MusicItem',
        ),
        migrations.DeleteModel(
            name='MusicItemTranslation',
        ),
    ]
