# Generated by Django 4.2.8 on 2023-12-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_musicitemtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicreleasetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='musicreleasetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='MusicRelease',
        ),
        migrations.DeleteModel(
            name='MusicReleaseTranslation',
        ),
    ]
